apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kkz-line-webhook
spec:
  template:
    spec:
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/kkz-line-webhook:latest
          ports:
            - containerPort: 8080
          env:
            - name: PUBLIC_BASE_URL
              value: https://SERVICE_URL
            - name: LINE_CHANNEL_SECRET
              valueFrom:
                secretKeyRef:
                  name: LINE_CHANNEL_SECRET
                  key: latest
            - name: LINE_CHANNEL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: LINE_CHANNEL_ACCESS_TOKEN
                  key: latest
